# Generated by Django 4.0.5 on 2023-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='noOfPost',
            field=models.IntegerField(default=0),
        ),
    ]
